name: Echo tagline

on:
  workflow_dispatch

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the tagline
        run: echo "This domain is for use in documentation examples without needing permission."
